CREATE DATABASE IF NOT EXISTS COLLEGE3;
USE COLLEGE3;
# YNIQUE KEY
CREATE TABLE TEMP1(
ID INT UNIQUE
);
INSERT INTO TEMP1 VALUES(101);
INSERT INTO TEMP1 VALUES(101); #ERROR BCOZ IT UNIQUE
SELECT * FROM TEMP1;

CREATE TABLE TEMP2(
#ID INT PRIMARY KEY    #1 TO CREATE PRIMARY KEY
ID INT,
NAME VARCHAR(20),
AGE INT,
CITY varchar(20),
primary key(ID)  #2 PRIMARY KEY
);
SELECT * FROM TEMP2;

