CREATE DATABASE COLLEGE2;
#DROP DATABASE COLLEGE2 ; 
USE COLLEGE2;

CREATE TABLE Student(
ID INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT NOT NULL
);

INSERT INTO Student VALUES(1,"Siddhi",22);
INSERT INTO Student VALUES(2,"Anisha",20);
INSERT INTO Student VALUES(3,"Aarya",12);
INSERT INTO Student VALUES(4,"Aarav",21);

# ADD COLUMN ADDRESS INTO STUDENT TABLE
alter table Student add ADDRESS VARCHAR(20);

#REMOVE COLUMN ADDRESS INTO STUDENT TABLE
ALTER TABLE Student drop column ADDRESS;

#MODIFY USED TO CHANGE IN DATA
ALTER TABLE Student MODIFY ID VARCHAR(10);

#RENAME COLUMN
ALTER TABLE Student rename column ID TO ROLL_NO;

# RENAME TO TABLE
ALTER TABLE student RENAME TO Stud;
SELECT*FROM Stud;
ALTER TABLE Stud RENAME TO Student;

#ADD PRIMARY KEY TO ROLL NO
alter table Student add primary key (ROLL_NO);


#table schema
DESC Student;
SELECT*FROM Student;